name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: apps/frontend
        run: |
          npm ci

      - name: Build frontend
        working-directory: apps/frontend
        run: |
          npm run build

  backend:
    name: Backend smoke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Backend sanity
        working-directory: apps/api
        run: |
          python -V
          pip install --upgrade pip
          pip install sqlalchemy alembic psycopg2-binary || true
          echo "backend sanity OK"
